/**
 * Web Forms API version 1.1
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: devcenter@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AuthenticationMethod.
* @enum {}
* @readonly
*/
export default class AuthenticationMethod {
    
        /**
         * value: "Biometric"
         * @const
         */
        "Biometric" = "Biometric";

    
        /**
         * value: "Email"
         * @const
         */
        "Email" = "Email";

    
        /**
         * value: "HTTPBasicAuth"
         * @const
         */
        "HTTPBasicAuth" = "HTTPBasicAuth";

    
        /**
         * value: "Kerberos"
         * @const
         */
        "Kerberos" = "Kerberos";

    
        /**
         * value: "KnowledgeBasedAuth"
         * @const
         */
        "KnowledgeBasedAuth" = "KnowledgeBasedAuth";

    
        /**
         * value: "None"
         * @const
         */
        "None" = "None";

    
        /**
         * value: "PaperDocuments"
         * @const
         */
        "PaperDocuments" = "PaperDocuments";

    
        /**
         * value: "Password"
         * @const
         */
        "Password" = "Password";

    
        /**
         * value: "RSASecureID"
         * @const
         */
        "RSASecureID" = "RSASecureID";

    
        /**
         * value: "SingleSignOn_CASiteminder"
         * @const
         */
        "SingleSignOn_CASiteminder" = "SingleSignOn_CASiteminder";

    
        /**
         * value: "SingleSignOn_InfoCard"
         * @const
         */
        "SingleSignOn_InfoCard" = "SingleSignOn_InfoCard";

    
        /**
         * value: "SingleSignOn_MicrosoftActiveDirectory"
         * @const
         */
        "SingleSignOn_MicrosoftActiveDirectory" = "SingleSignOn_MicrosoftActiveDirectory";

    
        /**
         * value: "SingleSignOn_Other"
         * @const
         */
        "SingleSignOn_Other" = "SingleSignOn_Other";

    
        /**
         * value: "SingleSignOn_Passport"
         * @const
         */
        "SingleSignOn_Passport" = "SingleSignOn_Passport";

    
        /**
         * value: "SingleSignOn_SAML"
         * @const
         */
        "SingleSignOn_SAML" = "SingleSignOn_SAML";

    
        /**
         * value: "Smartcard"
         * @const
         */
        "Smartcard" = "Smartcard";

    
        /**
         * value: "SSLMutualAuth"
         * @const
         */
        "SSLMutualAuth" = "SSLMutualAuth";

    
        /**
         * value: "X509Certificate"
         * @const
         */
        "X509Certificate" = "X509Certificate";

    

    /**
    * Returns a <code>AuthenticationMethod</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AuthenticationMethod} The enum <code>AuthenticationMethod</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

