/**
 * Web Forms API version 1.1
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: devcenter@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WebFormState.
* @enum {}
* @readonly
*/
export default class WebFormState {
    
        /**
         * value: "active"
         * @const
         */
        "active" = "active";

    
        /**
         * value: "draft"
         * @const
         */
        "draft" = "draft";

    

    /**
    * Returns a <code>WebFormState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WebFormState} The enum <code>WebFormState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

