/**
 * Web Forms API version 1.1
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: devcenter@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebFormInstanceEnvelopesInner model module.
 * @module model/WebFormInstanceEnvelopesInner
 * @version 1.1.0
 */
class WebFormInstanceEnvelopesInner {
    /**
     * Constructs a new <code>WebFormInstanceEnvelopesInner</code>.
     * @alias module:model/WebFormInstanceEnvelopesInner
     */
    constructor() { 
        
        WebFormInstanceEnvelopesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebFormInstanceEnvelopesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebFormInstanceEnvelopesInner} obj Optional instance to populate.
     * @return {module:model/WebFormInstanceEnvelopesInner} The populated <code>WebFormInstanceEnvelopesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebFormInstanceEnvelopesInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebFormInstanceEnvelopesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebFormInstanceEnvelopesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * Envelope Id
 * @member {String} id
 */
WebFormInstanceEnvelopesInner.prototype['id'] = undefined;






export default WebFormInstanceEnvelopesInner;

