/**
 * Web Forms API version 1.1
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: devcenter@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WebFormComponentType.
* @enum {}
* @readonly
*/
export default class WebFormComponentType {
    
        /**
         * value: "CheckboxGroup"
         * @const
         */
        "CheckboxGroup" = "CheckboxGroup";

    
        /**
         * value: "Date"
         * @const
         */
        "Date" = "Date";

    
        /**
         * value: "Email"
         * @const
         */
        "Email" = "Email";

    
        /**
         * value: "Number"
         * @const
         */
        "Number" = "Number";

    
        /**
         * value: "RadioButtonGroup"
         * @const
         */
        "RadioButtonGroup" = "RadioButtonGroup";

    
        /**
         * value: "Select"
         * @const
         */
        "Select" = "Select";

    
        /**
         * value: "TextBox"
         * @const
         */
        "TextBox" = "TextBox";

    

    /**
    * Returns a <code>WebFormComponentType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WebFormComponentType} The enum <code>WebFormComponentType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

