/**
 * Web Forms API version 1.1
 * The Web Forms API facilitates generating semantic HTML forms around everyday contracts. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: devcenter@docusign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebFormProperties model module.
 * @module model/WebFormProperties
 * @version 1.1.0
 */
class WebFormProperties {
    /**
     * Constructs a new <code>WebFormProperties</code>.
     * General information about the web form that is consistent across versions
     * @alias module:model/WebFormProperties
     */
    constructor() { 
        
        WebFormProperties.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebFormProperties</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebFormProperties} obj Optional instance to populate.
     * @return {module:model/WebFormProperties} The populated <code>WebFormProperties</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebFormProperties();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isPrivateAccess')) {
                obj['isPrivateAccess'] = ApiClient.convertToType(data['isPrivateAccess'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebFormProperties</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebFormProperties</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * User friendly Form name. This can be set via UI and/or API.
 * @member {String} name
 */
WebFormProperties.prototype['name'] = undefined;

/**
 * When a form is private, the Player will not be accessible via its URL unless a valid instance token is provided
 * @member {Boolean} isPrivateAccess
 */
WebFormProperties.prototype['isPrivateAccess'] = undefined;






export default WebFormProperties;

